### ISSUE TITLE
TypeError: function takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by Guang000** [xu-ji/IIC#54]
Traceback (most recent call last):
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "code/scripts/cluster/cluster_greyscale_twohead.py", line 496, in <module>
    train()
  File "code/scripts/cluster/cluster_greyscale_twohead.py", line 313, in train
    for tup in itertools.izip(*iterators):
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torchvision/datasets/mnist.py", line 97, in __getitem__
    img = self.transform(img)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 367, in __call__
    img = t(img)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torchvision/transforms/transforms.py", line 1003, in __call__
    return F.rotate(img, angle, self.resample, self.expand, self.center, self.fill)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/torchvision/transforms/functional.py", line 729, in rotate
    return img.rotate(angle, resample, expand, center, fillcolor=fill)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/PIL/Image.py", line 1871, in rotate
    return self.transform((w, h), AFFINE, matrix, resample, fillcolor=fillcolor)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/PIL/Image.py", line 2161, in transform
    im = new(self.mode, size, fillcolor)
  File "/local_home/guang_local/anaconda3/envs/py2/lib/python2.7/site-packages/PIL/Image.py", line 2331, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)

**Comment by ThibaultGROUEIX** [comment]
How did you solve it? In case you had it, it's always a good thing to post the solution for others.
I've run into the same problem and solved it by reinstalling torchvision>=0.5.0 as discussed [here](https://stackoverflow.com/questions/59659146/could-not-import-pillow-version-from-pil)
Best

**Comment by ThibaultGROUEIX** [comment]
How did you solve it? In case you had it, it's always a good thing to post the solution for others.
I've run into the same problem and solved it by installing a new python 2.7 env with the specs from [here](https://github.com/xu-ji/IIC/blob/master/package_versions.txt).
Cheers

**Comment by wzm2256** [comment]
How do you solve this problem?

**Comment by wzm2256** [comment]
For future reference. I give my solution here.
I spent a whole afternoon investigating this. It turns out to be a bug in the newer torch.
https://github.com/pytorch/vision/issues/1759
As mentioned in the above link, a work around is to add fill=(0,) in the RandomRotation transformation.
Specifically,
change 266 line of the file code/utils/cluster/transforms.py
from 
[torchvision.transforms.RandomRotation(config.rot_val)], p=0.5)]
to
[torchvision.transforms.RandomRotation(config.rot_val, fill=(0,))], p=0.5)]
will solve the problem.
